(() => {
  const cfg = window.FM_CONFIG || {};
  const tg = window.Telegram?.WebApp;
  const state = { months: 1, data: null, lang: (tg?.initDataUnsafe?.user?.language_code || navigator.language || 'ru').toLowerCase().startsWith('ru') ? 'ru' : 'en' };
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const dict = {
    en:{workspace:'YOUR WORKSPACE',hello:'Hello',heroText:'Fofan Flow, subscription and activity in one account.',actionsCycle:'actions this cycle',launches:'Launches',last7:'last 7 days',version:'Version',licenseKey:'License key',choosePlan:'Choose a plan',appTitle:'Application',appText:'Fast editing tools for After Effects and Premiere Pro.',download:'Download',soon:'Soon',whatInside:"What's inside",silence:'Remove silence',subs:'Subtitles',beats:'Beat markers',plans:'PLANS',chooseYour:'Choose your Flow',oneAction:'One completed plugin operation = 1 action.',manualPay:'Payment is currently confirmed manually by receipt in Telegram.',connected:'Connected',referrals:'Referrals',invite:'Copy invite link',news:'News',support:'Support',privacy:'Privacy Policy',terms:'Terms of Use'},
    ru:{workspace:'ТВОЁ ПРОСТРАНСТВО',hello:'Привет',heroText:'Fofan Flow, подписка и активность — в одном кабинете.',actionsCycle:'действий в цикле',launches:'Запуски',last7:'за 7 дней',version:'Версия',licenseKey:'Ключ лицензии',choosePlan:'Выбрать тариф',appTitle:'Приложение',appText:'Инструменты для быстрого монтажа в After Effects и Premiere Pro.',download:'Скачать',soon:'Скоро',whatInside:'Что внутри',silence:'Удаление пауз',subs:'Субтитры',beats:'Маркеры по битам',plans:'ТАРИФЫ',chooseYour:'Выбери свой Flow',oneAction:'Одна завершённая операция в плагине = 1 действие.',manualPay:'Оплата сейчас подтверждается вручную по чеку в Telegram.',connected:'Подключён',referrals:'Рефералы',invite:'Скопировать приглашение',news:'Новости',support:'Поддержка',privacy:'Политика конфиденциальности',terms:'Условия использования'}
  };
  const tr = k => dict[state.lang][k] || k;
  function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
  function nav(name){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===`screen-${name}`));$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));window.scrollTo({top:0,behavior:'smooth'});tg?.HapticFeedback?.selectionChanged()}
  function money(n){return new Intl.NumberFormat(state.lang==='ru'?'ru-RU':'en-US').format(n)+' ₽'}
  function demo(){return {user:{first_name:'Fofan',username:'4fan777',referrals:0,referral_link:'https://t.me/'+(cfg.botUsername||'bot')+'?start=ref_demo'},subscription:null,usage:{used:0,limit:0,percent:0,cycle_ends_at:null},activity:{launches_7d:0},app:{version:'3.1.0',windows_url:cfg.windowsDownloadUrl||''},plans:[{code:'basic',name:'Basic',monthly_price:380,token_limit:350,devices:1,features:['350 действий каждые 7 дней','Все основные функции','1 устройство']},{code:'pro',name:'Pro',monthly_price:490,token_limit:750,devices:1,features:['750 действий каждые 7 дней','Premium packs','Ранний доступ и приоритетная поддержка']},{code:'unlimit',name:'Unlimit',monthly_price:780,token_limit:-1,devices:2,features:['Безлимитные действия','Premium packs','2 устройства']}],news:[{title:'Fofan Montage Mini App',body:'Личный кабинет готовится к запуску.',published_at:new Date().toISOString()}]}}
  async function bootstrap(){
    const initData=tg?.initData||'';
    if(!initData && cfg.demoOutsideTelegram){state.data=demo();render();return}
    try{const r=await fetch(cfg.apiUrl.replace(/\/$/,'')+'/v1/bootstrap',{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':initData},body:'{}'});if(!r.ok)throw new Error((await r.json()).message||'API');state.data=await r.json();$('#connection').textContent='ONLINE';render();}
    catch(e){$('#connection').textContent='OFFLINE';$('#connection').style.color='#98989d';state.data=demo();render();toast(state.lang==='ru'?'Демо-режим: backend недоступен':'Demo mode: backend unavailable')}
  }
  function render(){const d=state.data,u=d.user||{},s=d.subscription,usage=d.usage||{};$('#first-name').textContent=u.first_name||'монтажёр';$('#profile-name').textContent=[u.first_name,u.last_name].filter(Boolean).join(' ')||'Fofan';$('#profile-username').textContent=u.username?'@'+u.username:'Telegram';$('#avatar').textContent=(u.first_name||'FM').slice(0,2).toUpperCase();$('#plan-badge').textContent=s?.plan_name||'FREE';$('#expiry').textContent=s?.expires_at?new Date(s.expires_at).toLocaleDateString(state.lang==='ru'?'ru-RU':'en-US'):(state.lang==='ru'?'Без подписки':'No subscription');let lim=usage.limit===-1?'∞':(usage.limit||0);$('#usage-value').textContent=`${usage.used||0} / ${lim}`;let p=Math.min(100,usage.percent||0);$('#usage-percent').textContent=usage.limit===-1?'∞':p+'%';$('#usage-bar').style.width=p+'%';$('#usage-ring').style.background=`conic-gradient(var(--accent) ${p}%,var(--track) 0)`;$('#cycle-label').textContent=usage.cycle_ends_at?((state.lang==='ru'?'Обновится ':'Resets ')+new Date(usage.cycle_ends_at).toLocaleDateString()):(state.lang==='ru'?'Обновится после активации':'Starts after activation');$('#launches').textContent=d.activity?.launches_7d||0;$('#version').textContent=d.app?.version||'3.1.0';$('#download-meta').textContent=`v${d.app?.version||'3.1.0'} · Windows`;$('#license-key').textContent=s?.license_key||((state.lang==='ru')?'Нет активного ключа':'No active key');$('#referrals').textContent=(u.referrals||0)+' / 10';renderPlans();renderNews();}
  function renderPlans(){const box=$('#plan-list');box.innerHTML='';const discounts={1:0,3:.05,6:.10,12:.15};for(const p of state.data.plans||[]){const total=Math.round(p.monthly_price*state.months*(1-discounts[state.months]));const a=document.createElement('article');a.className='plan '+(p.code==='pro'?'featured':'');a.innerHTML=`<h3>${p.name}</h3><div class="price">${money(total)} <small>/ ${state.months} мес.</small></div><ul>${(p.features||[]).map(f=>`<li>${f}</li>`).join('')}</ul><button class="primary">${state.lang==='ru'?'Выбрать':'Choose'}</button>`;a.querySelector('button').onclick=()=>buy(p.code);box.appendChild(a)}}
  function renderNews(){const b=$('#news-list');b.innerHTML='';for(const n of state.data.news||[]){const a=document.createElement('article');a.className='news-item';a.innerHTML=`<time>${new Date(n.published_at).toLocaleDateString()}</time><h4></h4><p></p>`;a.querySelector('h4').textContent=n.title;a.querySelector('p').textContent=n.body;b.appendChild(a)}if(!b.children.length)b.innerHTML='<article class="news-item"><p>Пока без новостей.</p></article>'}
  function buy(code){const tribute=(cfg.tributeLinks||{})[code];if(tribute){tg?.openTelegramLink?tg.openTelegramLink(tribute):location.href=tribute;return}if(!cfg.botUsername||cfg.botUsername==='YOUR_BOT_USERNAME'){toast('Сначала укажите username бота в config.js');return}const url=`https://t.me/${cfg.botUsername}?start=buy_${code}_${state.months}`;tg?.openTelegramLink?tg.openTelegramLink(url):location.href=url}
  const legal={privacy:`<div class="legal-copy"><h2>Политика конфиденциальности</h2><p>Редакция: 22.07.2026.</p><p>Сервис обрабатывает Telegram ID, имя, username, язык, сведения о подписке, запусках и расходе действий. Эти данные нужны для входа, лицензирования, лимитов, поддержки и защиты от злоупотреблений.</p><p>Ключи и технические идентификаторы защищаются; платёжные реквизиты банковских карт сервис не хранит. Данные могут обрабатываться Telegram, GitHub Pages и Cloudflare по их правилам.</p><p>Запрос на доступ или удаление данных направляется в поддержку через Telegram.</p><p class="notice">Это технический проект политики. Перед публичным приёмом платежей документ должен проверить законный совершеннолетний продавец или специалист.</p></div>`,terms:`<div class="legal-copy"><h2>Условия использования</h2><p>Fofan Flow предоставляется по подписке для использования в совместимых версиях Adobe After Effects / Premiere Pro. Один завершённый инструмент = одно действие. Basic: 350 действий/7 дней; Pro: 750/7 дней; Unlimit: без лимита. Неиспользованные действия не переносятся.</p><p>Trial действует 1 день и включает 50 действий; premium packs недоступны. Basic и Pro — 1 устройство, Unlimit — 2 устройства. Обход лицензии, перепродажа ключа и вредоносное использование запрещены.</p><p>Оплата по чеку и коммерческая оферта не должны публиковаться до оформления законного продавца. До этого интерфейс оплаты считается тестовым и не является публичной офертой.</p><p class="notice">Владелец проекта несовершеннолетний и пока не указал зарегистрированный статус продавца. Публичные продажи необходимо запускать через законного совершеннолетнего представителя/продавца и после проверки документов.</p></div>`};
  document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n)nav(n.dataset.nav);const m=e.target.closest('[data-modal]');if(m){$('#modal-body').innerHTML=legal[m.dataset.modal];$('#modal').showModal()}});$$('#periods button').forEach(b=>b.onclick=()=>{$$('#periods button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.months=+b.dataset.months;renderPlans()});$('#copy-key').onclick=()=>navigator.clipboard.writeText(state.data?.subscription?.license_key||'').then(()=>toast('Скопировано'));$('#copy-ref').onclick=()=>navigator.clipboard.writeText(state.data?.user?.referral_link||'').then(()=>toast('Ссылка скопирована'));$('#download-win').onclick=()=>{const u=cfg.windowsDownloadUrl||state.data?.app?.windows_url;if(u)tg?.openLink?tg.openLink(u):open(u,'_blank','noopener');else toast('Ссылка на установщик пока не опубликована')};$('#support-link').href='https://t.me/'+(cfg.supportUsername||'dwayne633');$('#modal-close').onclick=()=>$('#modal').close();$$('[data-i18n]').forEach(x=>x.textContent=tr(x.dataset.i18n));const tl=cfg.tributeLinks||{};if(tl.basic&&tl.pro&&tl.unlimit){const per=$('#periods');if(per)per.style.display='none'}
  tg?.ready();tg?.expand();tg?.setHeaderColor?.('#000000');tg?.setBackgroundColor?.('#000000');bootstrap();
})();
