(() => {
  const cfg = window.FM_CONFIG || {};
  const tg = window.Telegram?.WebApp;
  const state = { months: 3, plan: 'basic', tool: 'tools', data: null, lang: (tg?.initDataUnsafe?.user?.language_code || navigator.language || 'ru').toLowerCase().startsWith('ru') ? 'ru' : 'en' };
  const prices=globalThis.FM_PRICES||{};
  const planConfig=globalThis.FM_PLANS;
  const purchasableMonths=globalThis.FM_PURCHASABLE_MONTHS||[3,6,12];
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const dict = {
    en:{workspace:'YOUR WORKSPACE',hello:'Hello',heroText:'WADEONIX, subscription and activity in one account.',actionsCycle:'actions this cycle',launches:'Launches',last7:'last 7 days',version:'Version',licenseKey:'License key',choosePlan:'Choose a plan',appTitle:'Application',appText:'Fast editing tools for After Effects and Premiere Pro.',download:'Download',soon:'Soon',whatInside:"What's inside",silence:'Remove silence',subs:'Subtitles',beats:'Beat markers',plans:'PLANS',chooseYour:'Choose your plan',oneAction:'One completed plugin operation = 1 action.',manualPay:'Pay with Platega or Crypto Bot. The key is issued after payment confirmation.',connected:'Connected',referrals:'Referrals',invite:'Copy invite link',news:'News',support:'Support',privacy:'Privacy Policy',terms:'Terms of Use'},
    ru:{workspace:'ТВОЁ ПРОСТРАНСТВО',hello:'Привет',heroText:'WADEONIX, подписка и активность — в одном кабинете.',actionsCycle:'действий в цикле',launches:'Запуски',last7:'за 7 дней',version:'Версия',licenseKey:'Ключ лицензии',choosePlan:'Выбрать тариф',appTitle:'Приложение',appText:'Инструменты для быстрого монтажа в After Effects и Premiere Pro.',download:'Скачать',soon:'Скоро',whatInside:'Что внутри',silence:'Удаление пауз',subs:'Субтитры',beats:'Маркеры по битам',plans:'ТАРИФЫ',chooseYour:'Выбери свой тариф',oneAction:'Одна завершённая операция в плагине = 1 действие.',manualPay:'Оплата через Platega или Crypto Bot. После подтверждения ключ выдаётся автоматически.',connected:'Подключён',referrals:'Рефералы',invite:'Скопировать приглашение',news:'Новости',support:'Поддержка',privacy:'Политика конфиденциальности',terms:'Условия использования'}
  };
  const tr = k => dict[state.lang][k] || k;
  function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
  function nav(name){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===`screen-${name}`));$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));window.scrollTo({top:0,behavior:'smooth'});tg?.HapticFeedback?.selectionChanged()}
  function renderTelegramAvatar(){const image=$('#telegram-avatar');const photoUrl=String(tg?.initDataUnsafe?.user?.photo_url||'').trim();if(!image||!photoUrl.startsWith('https://'))return;image.onload=()=>{image.hidden=false};image.onerror=()=>{image.hidden=true;image.removeAttribute('src')};image.src=photoUrl}
  function money(n){return new Intl.NumberFormat(state.lang==='ru'?'ru-RU':'en-US').format(n)+' ₽'}
  function demo(){return {user:{first_name:'Wade',username:'4fan777',referrals:0,referral_link:'https://t.me/'+(cfg.botUsername||'bot')+'?start=ref_demo'},subscription:null,usage:{used:0,limit:0,percent:0,cycle_ends_at:null},activity:{launches_7d:0},app:{version:cfg.appVersion||'5.0.0',windows_url:cfg.windowsDownloadUrl||''},trial_available:true,plans:[{code:'basic',name:'Core',monthly_price:490,token_limit:350,devices:1,features:['Все функции WADEONIX','350 действий в неделю','1 устройство']},{code:'pro',name:'Pro',monthly_price:780,token_limit:350,devices:1,features:['Всё из Core','Premium Projects','Приоритетная поддержка']},{code:'unlimit',name:'Ultimate',monthly_price:1750,token_limit:-1,devices:2,features:['Всё из Pro','Безлимит действий','2 устройства','WADEONIX Essentials Pack']}],news:[{title:'WADEONIX Mini App',body:'Личный кабинет готовится к запуску.',published_at:new Date().toISOString()}]}}
  async function bootstrap(){
    const initData=tg?.initData||'';
    if(!initData && cfg.demoOutsideTelegram){state.data=demo();render();return}
    try{const r=await fetch(cfg.apiUrl.replace(/\/$/,'')+'/v1/bootstrap',{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':initData},body:'{}'});if(!r.ok)throw new Error((await r.json()).message||'API');state.data=await r.json();$('#connection').textContent='ONLINE';render();}
    catch(e){$('#connection').textContent='OFFLINE';$('#connection').style.color='#98989d';state.data=demo();render();toast(state.lang==='ru'?'Демо-режим: backend недоступен':'Demo mode: backend unavailable')}
  }
  async function selectLicense(key){const initData=tg?.initData||'';if(!initData)throw new Error('Откройте кабинет через Telegram');const r=await fetch(cfg.apiUrl.replace(/\/$/,'')+'/v1/select-license',{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':initData},body:JSON.stringify({license_key:key})});const data=await r.json();if(!r.ok)throw new Error(data.message||'Не удалось подключить ключ');return data}
  function render(){const d=state.data,u=d.user||{},s=d.subscription,usage=d.usage||{};$('#first-name').textContent=u.first_name||'монтажёр';$('#profile-name').textContent=[u.first_name,u.last_name].filter(Boolean).join(' ')||'Wade';$('#profile-username').textContent=u.username?'@'+u.username:'Telegram';$('#avatar').textContent=(u.first_name||'WX').slice(0,2).toUpperCase();$('#plan-badge').textContent=s?.plan_name||'FREE';$('#expiry').textContent=s?.expires_at?new Date(s.expires_at).toLocaleDateString(state.lang==='ru'?'ru-RU':'en-US'):(state.lang==='ru'?'Без подписки':'No subscription');let lim=usage.limit===-1?'∞':(usage.limit||0);$('#usage-value').textContent=`${usage.used||0} / ${lim}`;let p=Math.min(100,usage.percent||0);$('#usage-percent').textContent=usage.limit===-1?'∞':p+'%';$('#usage-bar').style.width=p+'%';$('#usage-ring').style.background=`conic-gradient(var(--accent) ${p}%,var(--track) 0)`;$('#cycle-label').textContent=usage.cycle_ends_at?((state.lang==='ru'?'Обновится ':'Resets ')+new Date(usage.cycle_ends_at).toLocaleDateString()):(state.lang==='ru'?'Обновится после активации':'Starts after activation');$('#launches').textContent=d.activity?.launches_7d||0;const appVersion=cfg.appVersion||d.app?.version||'5.0.0';$('#version').textContent=appVersion;$('#download-meta').textContent=`v${appVersion} · Windows`;$('#license-key').textContent=s?.license_key||((state.lang==='ru')?'Нет активного ключа':'No active key');$('#referrals').textContent=(u.referrals||0)+' / 10';const trial=$('#trial-button');const available=d.trial_available!==false;trial.disabled=!available;trial.classList.toggle('trial-used',!available);trial.title=available?'Пробный период на 3 дня':'Пробный период уже использован';renderPlans();renderNews();}
  function renderPlans(){
    const plan=planConfig[state.plan],quote=globalThis.FM_QUOTE(state.plan,state.months);
    $('#screen-subs').dataset.plan=state.plan;
    $('#plan-name').textContent=plan.name;
    $('#plan-description').textContent=state.lang==='ru'?plan.description:plan.descriptionEn;
    $('#plan-counter').textContent=(Object.keys(planConfig).indexOf(state.plan)+1)+' / 3';
    $('#card-monthly').textContent=money(quote.monthly);
    $('#quote-monthly').textContent=money(quote.monthly);
    $('#plan-total').textContent=money(quote.total);
    $('#total-label').textContent=(state.months===12?'На год':state.months===3?'3 месяца':'6 месяцев')+' · Итого';
    $('#plan-saving').textContent='Экономия '+money(quote.saving);
    const planKeys=Object.keys(planConfig),planTabs=$('#plan-tabs');planTabs.style.setProperty('--plan-index',String(planKeys.indexOf(state.plan)));
    $$('#plan-tabs button').forEach(b=>{const active=b.dataset.plan===state.plan;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});
    $$('#periods button').forEach(b=>{const active=+b.dataset.months===state.months;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});
    const features=$('#plan-features');features.replaceChildren();
    for(const text of state.data?.plans?.find(p=>p.code===state.plan)?.features||[]){const li=document.createElement('li');li.textContent=text;features.append(li)}
    for(const element of [$('#plan-card'),$('.quote')]){element.classList.remove('switching');void element.offsetWidth;element.classList.add('switching')}
  }
  function renderNews(){const b=$('#news-list');b.innerHTML='';for(const n of state.data.news||[]){const a=document.createElement('article');a.className='news-item';a.innerHTML=`<time>${new Date(n.published_at).toLocaleDateString()}</time><h4></h4><p></p>`;a.querySelector('h4').textContent=n.title;a.querySelector('p').textContent=n.body;b.appendChild(a)}if(!b.children.length)b.innerHTML='<article class="news-item"><p>Пока без новостей.</p></article>'}
  let paymentBusy=false,paymentReturnChecked=false;
  function validSelection(code){return purchasableMonths.includes(state.months)&&Boolean(prices[code]?.[state.months])}
  function openPaymentSheet(){if(!validSelection(state.plan)){toast('Этот период недоступен');return}if(!tg?.initData){toast('Откройте Mini App через Telegram');return}$('#payment-sheet').showModal();tg?.HapticFeedback?.selectionChanged()}
  function paymentUrl(value,provider){try{const u=new URL(value),allowed=provider==='platega'?['pay.platega.io','app.platega.io']:['t.me','telegram.me','pay.crypt.bot','testnet-pay.crypt.bot'];return u.protocol==='https:'&&allowed.includes(u.hostname)&&!u.username&&!u.password?u.toString():''}catch{return''}}
  function requestId(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`}
  function setPaymentState(text,busy){paymentBusy=busy;const main=$('#continue-plan');main.disabled=busy;main.firstChild.textContent=text+' ';$$('[data-payment-provider]').forEach(button=>button.disabled=busy);$('#payment-cancel').disabled=busy}
  async function createCheckout(provider){if(paymentBusy)return;const loading=provider==='platega'?'Создаем оплату...':'Создаем счет...';setPaymentState(loading,true);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const response=await fetch(cfg.apiUrl.replace(/\/$/,'')+'/v1/payments/create',{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':tg?.initData||''},body:JSON.stringify({provider,plan:state.plan,period:state.months,request_id:requestId()}),signal:controller.signal});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Не удалось создать оплату');const url=paymentUrl(data.payment_url,provider);if(!url)throw new Error('Платежная ссылка недоступна');setPaymentState('Переходим к оплате...',true);sessionStorage.setItem('wadeonix_pending_order',String(data.order_id||''));$('#payment-sheet').close();if((url.startsWith('https://t.me/')||url.startsWith('https://telegram.me/'))&&tg?.openTelegramLink)tg.openTelegramLink(url);else if(tg?.openLink)tg.openLink(url);else open(url,'_blank','noopener,noreferrer')}catch(error){setPaymentState('Продолжить',false);toast(error.name==='AbortError'?'Сервис оплаты не ответил. Попробуйте снова':(error.message||'Не удалось создать оплату'))}finally{clearTimeout(timer)}}
  async function checkReturnedPayment(){if(paymentReturnChecked)return;const query=new URLSearchParams(location.search),orderId=query.get('payment')||sessionStorage.getItem('wadeonix_pending_order');if(!orderId||!tg?.initData)return;paymentReturnChecked=true;toast('Проверяем оплату...');try{const response=await fetch(cfg.apiUrl.replace(/\/$/,'')+'/v1/payments/status',{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':tg.initData},body:JSON.stringify({order_id:Number(orderId)})});const data=await response.json();if(response.ok&&data.paid){sessionStorage.removeItem('wadeonix_pending_order');toast(`Оплата прошла${data.expires_at?' · до '+new Date(data.expires_at).toLocaleDateString('ru-RU'):''}`);await bootstrap()}else toast('Оплата пока не подтверждена')}catch{toast('Не удалось проверить оплату')}}
  const legal={privacy:`<div class="legal-copy"><h2>Политика конфиденциальности</h2><p>Редакция: 22.07.2026.</p><p>Сервис обрабатывает Telegram ID, имя, username, язык, сведения о подписке, запусках и расходе действий. Эти данные нужны для входа, лицензирования, лимитов, поддержки и защиты от злоупотреблений.</p><p>Ключи и технические идентификаторы защищаются; платёжные реквизиты банковских карт сервис не хранит. Данные могут обрабатываться Telegram, GitHub Pages и Cloudflare по их правилам.</p><p>Запрос на доступ или удаление данных направляется в поддержку через Telegram.</p><p class="notice">Это технический проект политики. Перед публичным приёмом платежей документ должен проверить законный совершеннолетний продавец или специалист.</p></div>`,terms:`<div class="legal-copy"><h2>Условия использования</h2><p>WADEONIX предоставляется по подписке для использования в совместимых версиях Adobe After Effects / Premiere Pro. Один завершённый инструмент = одно действие. Core: 350 действий/7 дней; Pro: 350 действий/7 дней и Premium Projects; Ultimate: без лимита. Неиспользованные действия не переносятся.</p><p>Trial действует 3 дня и включает 50 действий; Premium Projects недоступны. Core и Pro — 1 устройство, Ultimate — 2 устройства. Обход лицензии, перепродажа ключа и вредоносное использование запрещены.</p><p>Онлайн-оплата обрабатывается платёжным сервисом Platega. Сервис WADEONIX не хранит реквизиты банковских карт. После подтверждения оплаты ключ выдаётся автоматически.</p><p class="notice">Владелец проекта несовершеннолетний и пока не указал зарегистрированный статус продавца. Публичные продажи необходимо запускать через законного совершеннолетнего представителя/продавца и после проверки документов.</p></div>`};
  document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n)nav(n.dataset.nav);const m=e.target.closest('[data-modal]');if(m){$('#modal-body').innerHTML=legal[m.dataset.modal];$('#modal').showModal()}});$$('#periods [data-months]').forEach(b=>b.onclick=()=>{$$('#periods button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.months=+b.dataset.months;renderPlans()});$('#trial-button').onclick=()=>{if(state.data?.trial_available===false){toast('Пробный период уже использован');return}const url=`https://t.me/${cfg.botUsername||'WadeOnix_Bot'}?start=trial_3d`;tg?.openTelegramLink?tg.openTelegramLink(url):open(url,'_blank','noopener');toast('Бот выдаст ключ и синхронизирует его с кабинетом')};$('#copy-key').onclick=()=>navigator.clipboard.writeText(state.data?.subscription?.license_key||'').then(()=>toast('Скопировано'));$('#copy-ref').onclick=()=>navigator.clipboard.writeText(state.data?.user?.referral_link||'').then(()=>toast('Ссылка скопирована'));$('#download-win').onclick=()=>{const u=cfg.windowsDownloadUrl||state.data?.app?.windows_url;if(u)tg?.openLink?tg.openLink(u):open(u,'_blank','noopener');else toast('Ссылка на установщик пока не опубликована')};$('#support-link').href='https://t.me/'+(cfg.supportUsername||'itsWade');$('#modal-close').onclick=()=>$('#modal').close();$$('[data-i18n]').forEach(x=>x.textContent=tr(x.dataset.i18n));const tl=cfg.tributeLinks||{};if(tl.basic&&tl.pro&&tl.unlimit){const per=$('#periods');if(per)per.style.display='none'}
  const keyForm=$('#key-form'),keyInput=$('#new-license-key'),saveKey=$('#save-key');$('#change-key').onclick=()=>{keyForm.hidden=false;keyInput.focus()};$('#cancel-key').onclick=()=>{keyForm.hidden=true;keyInput.value=''};keyForm.onsubmit=async e=>{e.preventDefault();const key=keyInput.value.trim().toUpperCase();if(key.length<8){toast('Введите полный ключ');return}saveKey.disabled=true;saveKey.textContent='Проверяю…';try{await selectLicense(key);await bootstrap();keyForm.hidden=true;keyInput.value='';toast('Ключ подключён, статистика обновлена')}catch(err){toast(err.message||'Ошибка ключа')}finally{saveKey.disabled=false;saveKey.textContent='Подключить'}};renderTelegramAvatar();tg?.ready();tg?.expand();tg?.setHeaderColor?.('#000000');tg?.setBackgroundColor?.('#000000');bootstrap();
  const toolGroups={
    tools:{label:'Инструменты',title:'Обработка',items:[['scissors','Убрать паузы','Вырезает тишину на таймлайне'],['caption','Субтитры','Распознаёт речь и создаёт субтитры'],['ban','Цензура','Находит мат и запикивает его'],['music','Маркеры по битам','Ставит маркеры в ритм музыки'],['sliders','Шумодав','Очищает звук от фонового шума']]},
    record:{label:'Запись',title:'Записывай',items:[['mic','Запись голоса','Записывайте озвучку для своего проекта'],['music','На таймлайн','Добавляйте готовую запись в проект']]},
    fx:{label:'Fast FX',title:'Создавай',items:[['sliders','Fast FX','Быстрые эффекты для вашего монтажа'],['grid','Пресеты','Готовые настройки в одном месте']]},
    sfx:{label:'SFX',title:'Звучание',items:[['music','Библиотека звуков','Звуковые эффекты по категориям'],['search','Поиск по названию','Найдите нужный звук за секунды'],['folder','Мои звуки','Сохранённые звуки на вашем компьютере']]},
    motion:{label:'Motion',title:'Движение',items:[['motion','Motion','Анимация и движение для ваших проектов']]}
  };
  const iconPaths={scissors:'<circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><path d="m8 8 13 13M8 16 21 3"/>',caption:'<rect x="2" y="4" width="20" height="16" rx="4"/><path d="M10 9H6v6h4m8-6h-4v6h4"/>',ban:'<circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/>',music:'<path d="M9 18V5l12-2v13M9 8l12-2"/><ellipse cx="5.5" cy="18" rx="3.5" ry="3"/><ellipse cx="17.5" cy="16" rx="3.5" ry="3"/>',sliders:'<path d="M2 6h7m4 0h9M2 18h12m4 0h4"/><circle cx="11" cy="6" r="2"/><circle cx="16" cy="18" r="2"/>',mic:'<rect x="8" y="2" width="8" height="13" rx="4"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3m-4 0h8"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',search:'<circle cx="10" cy="10" r="7"/><path d="m15 15 7 7"/>',folder:'<path d="M3 6h7l2 3h9v11H3Z"/>',motion:'<path d="m10 4 9 8-9 8M3 4l9 8-9 8"/>'};
  function renderTools(){
    const tabs=$('#tool-tabs');tabs.replaceChildren();
    Object.entries(toolGroups).forEach(([key,group])=>{const b=document.createElement('button');b.textContent=group.label;b.dataset.tool=key;b.setAttribute('role','tab');b.setAttribute('aria-selected',String(state.tool===key));b.classList.toggle('active',state.tool===key);b.onclick=()=>{state.tool=key;renderTools()};tabs.append(b)});
    const group=toolGroups[state.tool];$('#workspace-title').textContent=group.title;
    $('#tool-list').innerHTML=group.items.map(([icon,name,description])=>`<article class="tool-row"><span class="tool-icon"><svg viewBox="0 0 24 24" aria-hidden="true">${iconPaths[icon]}</svg></span><div><h4>${name}</h4><p>${description}</p></div></article>`).join('');
  }
  $$('#plan-tabs button').forEach(b=>b.onclick=()=>{state.plan=b.dataset.plan;renderPlans()});
  $('#plan-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const keys=Object.keys(planConfig),step=e.key==='ArrowRight'?1:-1;state.plan=keys[(keys.indexOf(state.plan)+step+keys.length)%keys.length];renderPlans();$('#plan-tabs .active').focus()});
  let touchStart;
  $('#plan-card').addEventListener('touchstart',e=>{touchStart={x:e.touches[0].clientX,y:e.touches[0].clientY}},{passive:true});
  $('#plan-card').addEventListener('touchend',e=>{if(!touchStart)return;const dx=e.changedTouches[0].clientX-touchStart.x,dy=e.changedTouches[0].clientY-touchStart.y;touchStart=null;if(Math.abs(dx)<45||Math.abs(dx)<Math.abs(dy))return;const keys=Object.keys(planConfig);state.plan=keys[Math.max(0,Math.min(keys.length-1,keys.indexOf(state.plan)+(dx<0?1:-1)))];renderPlans()},{passive:true});
  $('#continue-plan').onclick=openPaymentSheet;
  $$('[data-payment-provider]').forEach(button=>button.onclick=()=>createCheckout(button.dataset.paymentProvider));
  $('#payment-cancel').onclick=()=>{if(!paymentBusy)$('#payment-sheet').close()};
  function launchScreen(){
    const query=new URLSearchParams(location.search),hash=new URLSearchParams(location.hash.slice(1));
    const values=[query.get('tab'),query.get('screen'),query.get('route'),query.get('startapp'),query.get('start_param'),query.get('tgWebAppStartParam'),hash.get('tab'),hash.get('tgWebAppStartParam'),tg?.initDataUnsafe?.start_param,new URLSearchParams(tg?.initData||'').get('start_param'),location.hash.slice(1)];
    for(const value of values){const v=String(value||'').toLowerCase().replace(/^\//,'');if(['subs','plans','tariffs','pricing','subscribe','subscription','buy'].includes(v)||v.startsWith('buy_'))return 'subs';if(['app','me','home'].includes(v))return v}
    return 'app';
  }
  function safeArea(){const inset=tg?.safeAreaInset||{},content=tg?.contentSafeAreaInset||{};for(const edge of ['top','bottom','left','right'])document.documentElement.style.setProperty('--tg-safe-'+edge,((inset[edge]||0)+(content[edge]||0))+'px')}
  safeArea();tg?.onEvent?.('safeAreaChanged',safeArea);tg?.onEvent?.('contentSafeAreaChanged',safeArea);
  renderTools();nav(launchScreen());setTimeout(checkReturnedPayment,250);
})();
